### ISSUE TITLE
using prepareForSegue to pass data from the the collection view to table view 

### ISSUE THREAD

**Issue by alialki** [terminatorover/RGCardViewLayout#6]
hi there i am trying to use prepareForSegue to pass data from the collection view when the button is used to a tableview controller but i am not having any luck have you done this or tried this so i can have some help regarding this 
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
  
  goalVideoListTableViewController *goalvc = [segue destinationViewController];
  NSIndexPath *indexPath = [UICollectionViewLayout indexPathForCell:sender];
  goalvc.scorerEntry = [self.scorerArray objectAtIndex:indexPath.section];
  }

i have no idea how to do so and getting error on indexPathForCell:sender

any help would be great

**Comment by terminatorover** [comment]
what is the button you are referring to .Or, what is sender in the prepareForSegue: method ?

**Comment by alialki** [comment]
i have designed the cards in a way to get data from a plist of arrays of dictionaries and changed the button view guide in a way to load a list of videos in a table view which is again loaded from the same plist for each of the card entries but the thing is i can't get it to pass the data to the table view I am not sure if my explaining is understandable or not and if it is if what i am saying even possible?

**Comment by terminatorover** [comment]
i'm not entirely sure what you mean. However, my guess is that you're not hooking things up properly. Check if the prepareForSegue: method is even called, and if it is check if it is the sender is a cell. Note that the prepareForSegue method won't be called automatically just because you tapped on the View Guide button so you should have some logic to perform the segue.
